### ISSUE TITLE
Fetch Question: One user vs. all the data?

### ISSUE THREAD

**Issue by Garrett-Iannuzzi** [JamesRexMiller4/refactortractor#3]
Something to think about.....

According to the speck we will be fetching different data for each category (sleep, activity, hydration, and user) , to me this means we could leave the class structure the relatively the same, passing in the data to each class from the scripts file. If we do this I was just wondering everyones thoughts on this? This could also be a question for refactoring the class structure.

**Comment by JamesRexMiller4** [comment]
Still not 100% on the fetch process, but from what I understand we will be grabbing the data and also inserting new data into the original dataset. Maybe we could look into some inheritance where each repository now comes with a method for inserting new data for its respective dataset?
